// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC6i-wv87oBNKgMzIEY_5JF4eE3U3zyTRo',
    appId: '1:885925998310:web:6269cf700963c9605b9527',
    messagingSenderId: '885925998310',
    projectId: 'notificacao-77a93',
    authDomain: 'notificacao-77a93.firebaseapp.com',
    storageBucket: 'notificacao-77a93.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDL7dhnNR_lHXC8YlGo9SmKPfv-e4BZvrQ',
    appId: '1:885925998310:android:3612b5396cc2ec345b9527',
    messagingSenderId: '885925998310',
    projectId: 'notificacao-77a93',
    storageBucket: 'notificacao-77a93.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD1xGp6VW8Kta86wATJ1r8EC3jJhIFiPz4',
    appId: '1:885925998310:ios:cb2194354cc066b25b9527',
    messagingSenderId: '885925998310',
    projectId: 'notificacao-77a93',
    storageBucket: 'notificacao-77a93.firebasestorage.app',
    iosBundleId: 'com.example.notificacao',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD1xGp6VW8Kta86wATJ1r8EC3jJhIFiPz4',
    appId: '1:885925998310:ios:cb2194354cc066b25b9527',
    messagingSenderId: '885925998310',
    projectId: 'notificacao-77a93',
    storageBucket: 'notificacao-77a93.firebasestorage.app',
    iosBundleId: 'com.example.notificacao',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC6i-wv87oBNKgMzIEY_5JF4eE3U3zyTRo',
    appId: '1:885925998310:web:69e4025a4beef0d35b9527',
    messagingSenderId: '885925998310',
    projectId: 'notificacao-77a93',
    authDomain: 'notificacao-77a93.firebaseapp.com',
    storageBucket: 'notificacao-77a93.firebasestorage.app',
  );
}
